#!/bin/bash
#SBATCH --job-name=bart_ner
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -t 0-48:00
#SBATCH -p rtx8000
#SBATCH --mem=200000
#SBATCH -o /scratch/zt2080/shizhe/eres/BARTNER/bart_large0922.o
#SBATCH -e /scratch/zt2080/shizhe/eres/BARTNER/bart_large0922.e
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=8
#SBATCH --mail-user=318112194@qq.com
#SBATCH --gres=gpu:1

python train.py
